### ISSUE TITLE
There are several copy of the SwiftNIO Locks

### ISSUE THREAD

**Issue by mengxiangyue** [apple/swift-metrics#95]
Hello, I find in `swift-log` and `swift-service-lifecycle` also include the copy of `SwiftNIO Locks`, do you think split it to a standalone framework?

[https://github.com/apple/swift-log/blob/main/Sources/Logging/Locks.swift](https://github.com/apple/swift-log/blob/main/Sources/Logging/Locks.swift)
[https://github.com/swift-server/swift-service-lifecycle/blob/main/Sources/Lifecycle/Locks.swift](https://github.com/swift-server/swift-service-lifecycle/blob/main/Sources/Lifecycle/Locks.swift)

**Comment by ktoso** [comment]
Hi there,
no, we are not going to make a standalone "locks" library. Copying around is painful, but is better than committing to a library we do not want to support long-term.

With [Swift Concurrency](https://forums.swift.org/t/swift-concurrency-roadmap/41611) just around the corner, we'll be rather embracing those things and Swift Atomics, rather than exposing those lock libs.

Hope that explains it :)
